mailer:
  default_from: info@septeni.jp
  send_password_subject: Polaris password
login:
  login_block_number: 3
role:
  SUPER: 1
  AGENCY: 3
  CLIENT: 2
user:
  deactive: 1
  active: 0
MAX_LENGTH_CLIENT_NAME: 40