mailer:
  default_from: info@septeni.jp
  send_password_subject: Polaris password
login:
  login_block_number: 3
role:
  SUPER: 1
  AGENCY: 3
  CLIENT: 2
user:
  deactive: 1
  active: 0
promotion:
  deleted: 1
  active: 0
client_user:
  deleted: 1
  active: 0
MAX_LENGTH_CLIENT_NAME: 40
MAX_LENGTH_PROMOTION_NAME: 40
media_category:
  1: 'Listing'
  2: 'Affiliate'
  3: 'Display'
media:
  1: 'Google'
  2: 'Yahoo'
  3: 'Google Adwords'
account:
  1: 'Account 1'
  2: 'Account 2'
  3: 'Account 3'
conversion:
  1: 'conversion 1'
  2: 'conversion 2'
  3: 'conversion 3'
