mailer:
  default_from: info@septeni.jp
  send_password_subject: Polaris password
login:
  login_block_number: 3
role:
  SUPER: 1
  AGENCY: 3
  CLIENT: 2
user:
  deactive: 1
  active: 0
promotion:
  deleted: 1
  active: 0
client_user:
  deleted: 1
  active: 0
MAX_LENGTH_NAME: 30
media_category:
  1: 'Listing'
  2: 'Display'
  3: 'Affiliate'
